apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  GATEWAY_CLIENT_SECRET: {{ .Values.secrets.GATEWAY_CLIENT_SECRET | b64enc | quote }}
  GATEWAY_CLIENT_ID: {{ .Values.secrets.GATEWAY_CLIENT_ID | b64enc | quote }}
  OPENMRS_PASSWORD: {{ .Values.secrets.OPENMRS_PASSWORD | b64enc | quote }}