apiVersion: v1
kind: Secret
metadata:
  name: {{ .Chart.Name }}-secrets
type: Opaque
data:
  Gateway__clientSecret: {{ .Values.secrets.GATEWAY_CLIENT_SECRET | b64enc | quote }}
  Gateway__clientId: {{ .Values.secrets.GATEWAY_CLIENT_ID | b64enc | quote }}
  OpenMrs__password: {{ .Values.secrets.OPENMRS_PASSWORD | b64enc | quote }}